# -*- coding: utf-8 -*-
"""U2 - Tema 3 .- Manejo de Archivos y Excepciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQeKYQqxYk1dGXIJF9-0cgFfXvGMb_ui

# Escribir un archivo
"""

with open("ejemplo.txt", "w") as archivo:
    archivo.write("Hola, este esto es un ejemplo.\n")
    archivo.write("Segunda línjemploea.\n")

"""# Leer archivo"""

with open("ejemplo.txt", "r") as archivo:
    contenido = archivo.read()
    print("Contenido del archivo:")
    print(contenido)

"""# Manejo de excepciones"""

try:
    numero = int(input("Ingresa un número: "))
    print("Número ingresado:", numero)
except ValueError:
    print("Error: Debes ingresar un número válido.")

try:
    with open("archivo_inexistente.txt", "r") as f:
        print(f.read())
except FileNotFoundError:
    print("El archivo no existe.")