# -*- coding: utf-8 -*-
"""U2 - Tema 1 .- Listas, Tuplas, Conjuntos y Diccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LzbMkMCqqG9PhiTjZ_jIYxUC8RGq31v

# **Listas (list)**

**Ejemplo básico**

Las listas son colecciones ordenadas y mutables (modificables). Permiten elementos duplicados y pueden contener diferentes tipos de datos.

**Ejemplo complejo**
"""

#chelle'] Lista de diccionarios con información de empleados
empleados = [
    {"nombre": "David", "edad": 30, "salario": 2500},
    {"nombre": "Madeleine", "edad": 25, "salario": 3200},
    {"nombre": "Carlos", "edad": 40, "salario": 4500},
    {"nombre": "Michelle", "edad": 35, "salario": 2800}
]

# Filtrar empleados con salario mayor a 3000 usando List Comprehension
empleados_altos_salarios = [e for e in empleados if e["salario"] > 3000]

print(empleados_altos_salarios)
# [{'nombre': 'Madeleine', 'edad': 25, 'salario': 3200}, {'nombre': 'Carlos', 'edad': 40, 'salario': 4500}]

# Ordenar empleados por edad (de menor a mayor)
empleados_ordenados = sorted(empleados, key=lambda e: e["edad"])
print(empleados_ordenados)

# Obtener solo los nombres de los empleados
nombres = [e["nombre"] for e in empleados]

print(nombres)  # ['Luis', 'Madeleine', 'Carlos', 'Mi

"""# **Tuplas (tuple)**

Las tuplas son colecciones ordenadas pero inmutables (no se pueden modificar después de su creación). Permiten elementos duplicados.

**Ejemplo básico**

# **Ejemplo complejo**
"""

# Diccionario con coordenadas (x, y) como clave y un valor asociado
ubicaciones = {
    (10, 20): "Punto A",
    (40, 40): "Punto B",
    (50, 60): "Punto C"
}

# Acceder a un valor usando una tupla como clave
print(ubicaciones[(40, 40)])  # Punto B

# Recorrer las coordenadas y los valores
for coord, lugar in ubicaciones.items():
    print(f"Coordenadas {coord} -> {lugar}")

# Desempaquetado de tuplas en una lista
puntos = [(1, 2), (3, 4), (5, 6)]
for num1, num2 in puntos:
    print(f"X: {num1} Y: {num2}")

# Definiendo una tupla
colores = ("rojo", "verde", "azul", "rojo")
print(colores)  # ('rojo', 'verde', 'azul', 'rojo')

# Acceder a elementos
print(colores[1])  # verde

# Intentar modificar (esto generará un error)
# colores[1] = "amarillo"  # TypeError: 'tuple' object does not support item assignment

# Recorrer tupla
for color in colores:
    print(color)

# Desempaquetado de tuplas
rojo, verde, azul, rojo = colores
print(verde, azul, rojo)  # rojo verde azul

"""# **Conjuntos (set)**

:Los conjuntos son colecciones no ordenadas y sin elementos duplicados. Son mutables pero sus elementos deben ser inmutables.

**Ejemplo básico**
"""

# num)Definiendo un conjunto
numeros = {6,7,8,9,41,44,44,9}
print(numeros)  # {1, 2, 3, 4} (Elimina duplicados automáticamente)

# Agregar elementos
numeros.add(5)
print(numeros)  # {1, 2, 3, 4, 5}

# Eliminar elementos
numeros.discard(44) # Usar discard() para evitar KeyError si el elemento no existe
print(numeros)  # {1, 2, 4, 5}

# Verificar si un elemento existe
print(6 in numeros)  # True

# Recorrer conjunto
index = 0
for num in numeros:
  print(num)

"""**Ejemplo complejo**"""

# Definiendo dos conjuntos
grupo_a = {"Luis", "Madeleine", "Carlos", "Michelle"}
grupo_b = {"Carlos", "Michelle", "Elena", "Pedro"}

# Unión de conjuntos (todos los elementos únicos)
union = grupo_a | grupo_b
print(union)  # {'Luis', 'Madeleine', 'Carlos', 'Michelle', 'Elena', 'Pedro'}

# Intersección (elementos comunes)
interseccion = grupo_a & grupo_b
print(interseccion)  # {'Carlos', 'Michelle'}

# Diferencia (elementos en A pero no en B)
diferencia = grupo_a - grupo_b
print(diferencia)  # {'Luis', 'Madeleine'}

# Diferencia simétrica (elementos que están en uno u otro, pero no en ambos)
diferencia_simetrica = grupo_a ^ grupo_b
print(diferencia_simetrica)  # {'Luis', 'Madeleine', 'Elena', 'Pedro'}

"""# **Diccionarios (dict)**

Los diccionarios son colecciones desordenadas de pares clave-valor. Permiten acceder a valores mediante una clave en lugar de un índice.

**Ejemplo básico**
"""

# Definiendo un diccionario
persona = {
    "nombre": "Juan",
    "edad": 25,
    "ciudad": "Quito"
}

print(persona)  # {'nombre': 'Juan', 'edad': 25, 'ciudad': 'Quito'}

# Acceder a valores
print(persona["edad"])  # 25

# Modificar valores
persona["edad"] = 30
print(persona)  # {'nombre': 'Juan', 'edad': 30, 'ciudad': 'Quito'}

# Agregar un nuevo par clave-valor
persona["profesion"] = "dentista"
print(persona)  # {'nombre': 'Juan', 'edad': 30, 'ciudad': 'Quito', 'profesion': 'Dentista'}

# Eliminar una clave
del persona["ciudad"]
print(persona)  # {'nombre': 'Juan', 'edad': 30, 'profesion': 'Doctor'}

# Recorrer un diccionario
for clave, valor in persona.items():
    print(f"{clave}: {valor}")

"""**Ejemplo complejo**"""

crearestudiante = {


    "Perez": {"id": 2023001, "correo":"ana@mail.com", "ingenieria": 8},
    "Gomez": {"id": 2023002, "correo":"luis@mail.com", "derecho": 9}
}

print(crearestudiante["Perez"]["correo"])



# Diccionario con información de estudiantes y sus calificaciones por materia
estudiantes = {
    "Juan": {"Matemáticas": 90, "Historia": 80, "Ciencias": 85},
    "Ana": {"Matemáticas": 95, "Historia": 75, "Ciencias": 90},
    "Carlos": {"Matemáticas": 70, "Historia": 85, "Ciencias": 80}
}

# Acceder a la calificación de una materia específica
print(estudiantes["Ana"]["Matemáticas"])  #95

# Promedio de notas por estudiante
for estudiante, materias in estudiantes.items():
    promedio = sum(materias.values()) / len(materias)
    print(f"{estudiante} tiene un promedio de {promedio:.2f}")

# Contar la cantidad de estudiantes con calificaciones mayores a 80 en Matemáticas
contador = sum(1 for e in estudiantes.values() if e["Matemáticas"] > 80)
print(f"Cantidad de estudiantes con más de 80 en Matemáticas: {contador}")

productos = {
    "Laptop":{"precio":1200, "stock":5},
    "Mouse":{"precio":20,"stock":50},
}

productos = {
    "Laptop":{"precio":1200, "stock":5},
    "Mouse":{"precio":20,"stock":50},
}



# Diccionario con información de estudiantes y sus calificaciones por materia
estudiantes = {
    "Juan": {"Matemáticas": 100, "Historia": 80, "Ciencias": 85},
    "Ana": {"Matemáticas": 95, "Historia": 125, "Ciencias": 90},
    "Carlos": {"Matemáticas": 70, "Historia": 85, "Ciencias": 80}
}

# Acceder a la calificación de una materia específica
print(estudiantes["Ana"]["Historia"])  # 75

# Promedio de notas por estudiante
for estudiante, materias in estudiantes.items():
    promedio = sum(materias.values()) / len(materias)
    print(f"{estudiante} tiene un promedio de {promedio:.2f}")

# Contar la cantidad de estudiantes con calificaciones mayores a 80 en Matemáticas
contador = sum(1 for e in estudiantes.values() if e["Matemáticas"] > 80)
print(f"Cantidad de estudiantes con más de 80 en Matemáticas: {contador}")

n = 5
while n > 0:
  print(n)
  n = n- 1
print("¡Despegue!")

"""# **Resumen**

[texto del enlace](https://)
"""