# -*- coding: utf-8 -*-
"""U2 - Tema 2 .- Funciones y Programación Modular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GOhzwaZkD-KJhnMROnle2_NODKJS2gep

# Función Básica
"""

def saludar(nombre):
    return f"Hola, {nombre}!"

print(saludar("Carlos"))

"""# Función con múltiples parámetros"""

def area_rectangulo(base, altura):
    return base * altura

print("Área del rectángulo:", area_rectangulo(5, 3))
print("area del rectangulo:", area_rectangulo(5, 5))

"""# Función con valor por defecto"""

def potencia(base, exponente=2):
    return base ** exponente

print("Potencia:", potencia(3))
print("Potencia con exponente 3:", potencia(3, 3))

"""# Usando módulos"""

import math
print("Raíz cuadrada de 16:", math.sqrt(16))