# -*- coding: utf-8 -*-
"""U3 - Tema 2 .- Polimorfismo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X0r23agCAYgg0L7tcN5TmIXZ7qDcagq

# Polimorfismo
"""

class Felino:
    def sonido(self):
        return "Miauuuuu"

class Perro:
    def sonido(self):
        return "Guauuuu"

class Pato:
    def sonido(self):
        return "Quack"

def hacer_sonar(animal):
    print(animal.sonido())

gato = Felino()
perro = Perro()
pato = Pato()

hacer_sonar(gato)