# -*- coding: utf-8 -*-
"""U3 - Tema 3 .- Creación de Scripts Automatizados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFRKSJZ5yXKQvEvl3Zia-Qn2jf0aRolY
"""

import os

# Simulación: lista de archivos en un directorio
archivos = ["foto1.jpg", "documento.pdf", "imagen2.png"]

for archivo in archivos:
    nombre, extension = os.path.splitext(archivo)
    nuevo_nombre = nombre + "_renombrado" + extension
    print(f"Renombrando: {archivo} -> {nuevo_nombre}")
    # os.rename(archivo, nuevo_nombre)  # Descomenta para usar en local

import os
import shutil

# Ruta de la carpeta a organizar (puedes cambiarla)
ruta_descargas = "/ruta/a/tu/carpeta"

# Diccionario de extensiones y sus carpetas destino
categorias = {
    "Imágenes": [".jpg", ".jpeg", ".png", ".gif", ".bmp"],
    "Documentos": [".pdf", ".docx", ".txt", ".xlsx", ".pptx"],
    "Videos": [".mp4", ".avi", ".mkv", ".mov"],
    "Audio": [".mp3", ".wav", ".aac"],
    "Comprimidos": [".zip", ".rar", ".tar", ".gz"],
    "Scripts": [".py", ".js", ".html", ".css"]
}

def organizar_archivos(ruta):
    # Verificar si la carpeta existe
    if not os.path.exists(ruta):
        print("La carpeta no existe.")
        return

    # Recorrer todos los archivos en la carpeta
    for archivo in os.listdir(ruta):
        ruta_archivo = os.path.join(ruta, archivo)

        # Solo procesar archivos (no carpetas)
        if os.path.isfile(ruta_archivo):
            nombre, extension = os.path.splitext(archivo)
            extension = extension.lower()

            # Determinar la categoría del archivo
            movido = False
            for categoria, extensiones in categorias.items():
                if extension in extensiones:
                    carpeta_destino = os.path.join(ruta, categoria)
                    # Crear la carpeta si no existe
                    if not os.path.exists(carpeta_destino):
                        os.makedirs(carpeta_destino)
                    # Mover el archivo
                    shutil.move(ruta_archivo, os.path.join(carpeta_destino, archivo))
                    print(f"Movido: {archivo} -> {categoria}")
                    movido = True
                    break

            # Si no coincide con ninguna categoría, lo dejamos donde está
            if not movido:
                print(f"No movido: {archivo}")

if __name__ == "__main__":
    organizar_archivos(ruta_descargas)
    print("✅ Organización completada.")