# -*- coding: utf-8 -*-
"""U3 - Tema 1 .- Clases, Herencias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cnYd1udKDa0P6uzymRPvfXB6pJd7dvqj

# Clase básica
"""

class Persona:
    def __init__(self, nombre, edad, curso, año):
        self.nombre = nombre
        self.edad = edad
        self.curso = curso
        self.año = año

    def presentarse(self):
        return f"Soy {self.nombre} tengo {self.edad} años. y estoy {self.curso} del {self.año} del semetres en la UNEMI"


persona = Persona("Julio", 67, "en sexto", 2025)
print(persona.presentarse())

"""# Herencia"""

class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def presentarse(self):
        return f"Soy {self.nombre} y tengo {self.edad} años."

class Estudiante(Persona):
    def __init__(self, nombre, edad, curso):
        super().__init__(nombre, edad)
        self.curso = curso

    def presentarse(self):
        return f"Soy {self.nombre}, tengo {self.edad} años y estudio {self.curso}. "

estudiante = Estudiante("Carlos", 67, "TIC - UNEMI")
estudiante1 = Estudiante("Javier", 35, "TICS - UNEMI")
print(estudiante.presentarse())
print(estudiante1.presentarse())

persona1 = Persona("Carlos Escalante", 67)
estudiante1 = Estudiante("Carlos", 67, "Python - UNEMI")
facultad1 = Facultad("TIC", "UNEMI")

print(persona1.presentarse())
print(estudiante1.presentarse())
print(facultad1.presentarse())

class Facultad:
    def __init__(self, nombre_facultad, universidad):
        self.nombre_facultad = nombre_facultad
        self.universidad = universidad

    def presentarse(self):
        return f"Soy la Facultad de {self.nombre_facultad} de la {self.universidad}."