# -*- coding: utf-8 -*-
"""U1 - Tema 3 .- Estructuras Condicionales y Bucles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qj0hj_CbBDa7pqNYBwO6XN0WLFIDVSnk

# **Estructuras Condicionales (if, elif, else)**
Las estructuras condicionales permiten ejecutar código dependiendo de una condición.

**Ejemplo: Condición simple (if)**
"""

edad = 18

if edad >= 18:
    print("Eres mayor de edad.")

"""**Ejemplo: Condición con else**"""

edad = 16

if edad >= 18:
    print("Eres mayor de edad.")
else:
    print("Eres menor de edad.")

"""**Ejemplo: Múltiples condiciones con elif**"""

nota = 85

if nota >= 90:
    print("Excelente")
elif nota >= 80:
    print("Muy bien")
elif nota >= 70:
    print("Bien")
else:
    print("Necesitas mejorar")

"""**Ejemplo: Condiciones anidadas**"""

usuario = "admin"
clave = "1234"

if usuario == "admin":
    if clave == "1234":
        print("Acceso concedido")
    else:
        print("Contraseña incorrecta")
else:
    print("Usuario no reconocido")

"""# **Bucles (while, for)**
Los bucles permiten ejecutar código repetidamente mientras se cumpla una condición.

**Ejemplo: Bucle while (se ejecuta mientras la condición sea True)**
"""

contador = 1

while contador <= 5:
    print("Número:", contador)
    contador += 1

"""**Ejemplo: Bucle for con rango (range)**"""

for i in range(1, 6):
    print("Número:", i)

"""**Ejemplo: Recorrer una lista con for**"""

frutas = ["Manzana", "Banana", "Cereza"]

for fruta in frutas:
    print("Fruta:", fruta)

"""**Ejemplo: Uso de break y continue**"""

for numero in range(1, 6):
    if numero == 3:
        break  # Termina el bucle cuando llega a 3
    print(numero)

print("----")

for numero in range(1, 6):
    if numero == 3:
        continue  # Salta la iteración cuando llega a 3
    print(numero)