# -*- coding: utf-8 -*-
"""U1 - Tema 2 .- Variables, Tipos de datos y Operadores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dP_DU-5YJKSp6v_ufymj3n_hF0ZK3Abv

# **Variables**

En Python, una variable es un contenedor para almacenar datos. No es necesario declarar su tipo explícitamente.
"""

# Declaración de variables
numero = 10           # Entero (int)
pi = 3.1416           # Flotante (float)
nombre = "Ana"        # Cadena de texto (str)
es_estudiante = True  # Booleano (bool)

# Mostrar valores y tipos
print("Número:", numero, "Tipo:", type(numero))
print("Pi:", pi, "Tipo:", type(pi))
print("Nombre:", nombre, "Tipo:", type(nombre))
print("Es estudiante:", es_estudiante, "Tipo:", type(es_estudiante))

"""# **Tipos de Datos**

Tipos Numéricos
"""

entero = 25        # int
decimal = 3.75     # float
complejo = 2 + 3j  # complex

print(type(entero))   # <class 'int'>
print(type(decimal))  # <class 'float'>
print(type(complejo)) # <class 'complex'>

"""Cadenas de Texto (String)"""

mensaje = "Hola, Python!"
print(mensaje)             # Hola, Python!
print(mensaje.upper())     # HOLA, PYTHON!
print(mensaje.lower())     # hola, python!
print(mensaje[0:4])        # Hola

"""Booleanos"""

es_mayor = 5 > 3  # True
es_menor = 2 > 8  # False

print(es_mayor)  # True
print(es_menor)  # False

"""Listas (List)"""

frutas = ["Manzana", "Banana", "Cereza"]
print(frutas[0])  # Manzana
frutas.append("Mango")
print(frutas)  # ['Manzana', 'Banana', 'Cereza', 'Mango']

"""Tuplas (Tuple)"""

coordenadas = (4, 5)
print(coordenadas[0])  # 4

"""Diccionarios (Dict)"""

persona = {"nombre": "Carlos", "edad": 25, "ciudad": "Quito"}
print(persona["nombre"])  # Carlos

"""# **Operadores en Python**

Operadores Aritméticos
"""

a = 10
b = 3

print(a + b)  # Suma -> 13
print(a - b)  # Resta -> 7
print(a * b)  # Multiplicación -> 30
print(a / b)  # División -> 3.3333
print(a // b) # División entera -> 3
print(a % b)  # Módulo -> 1
print(a ** b) # Potencia -> 1000

"""Operadores Relacionales (Comparación)"""

x = 5
y = 10

print(x > y)   # False
print(x < y)   # True
print(x == y)  # False
print(x != y)  # True

"""Operadores Lógicos"""

edad = 20
es_adulto = edad >= 18

print(es_adulto and True)  # True
print(es_adulto or False)  # True
print(not es_adulto)       # False

"""# Estructuras de datos mutables
Son aquellas que pueden modificarse después de su creación sin cambiar su identidad en memoria. Algunos ejemplos son:

**Listas (list)**
"""

lista = [1, 2, 3]
print("original: ", lista)  # [1, 2, 3]
lista.append(4)  # Modifica la lista original
print("mutado: ", lista)  # [1, 2, 3, 4]

"""Diccionarios (dict)"""

diccionario = {"a": 1, "b": 2}
print("original: ", diccionario)  # {'a': 1, 'b': 2}
diccionario["c"] = 3  # Modifica el diccionario original
print("mutado: ", diccionario)  # {'a': 1, 'b': 2, 'c': 3}

"""# Estructuras de datos inmutables
No pueden ser modificadas después de su creación. Si se desea cambiar su contenido, se debe crear una nueva instancia. Ejemplos:

**Tuplas (tuple)**
"""

tupla = (1, 2, 3)
tupla[0] = 4  # ❌ Esto generará un error

"""**Cadenas de texto (str)**"""

cadena = "Hola"
cadena[0] = "h"  # ❌ Esto generará un error

"""**Números (int, float, complex)**

"""

x = 10
x += 1  # Se crea una nueva variable en memoria en lugar de modificar la original

"""En resumen, ***listas, diccionarios, conjuntos y objetos personalizados pueden modificarse (mutables)***, mientras que ***tuplas, cadenas, números y conjuntos inmutables no pueden modificarse (inmutables)***."""