# -*- coding: utf-8 -*-
"""U4 - Tema 3 .-  Obtener y enviar datos a una API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpkpl6Zrez8Xap2r62cK-cIt6FIp8jAE
"""

import requests

# OBTENER DATOS
url = "https://jsonplaceholder.typicode.com/posts/1"
response = requests.get(url)
if response.status_code == 200:
    datos = response.json()
    print("Título del post:", datos["title"])
else:
    print("Error al obtener los datos")

# ENVIAR DATOS (POST)
nuevo_post = {
    "title": "Mi título",
    "body": "Contenido del post",
    "userId": 1
}

url_post = "https://jsonplaceholder.typicode.com/posts"
response_post = requests.post(url_post, json=nuevo_post)
if response_post.status_code == 201:
    print("Post creado:", response_post.json())
else:
    print("Error al crear el post")