# -*- coding: utf-8 -*-
"""U4 - Tema 1 .- Decoradores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6gTGDLQABqL4Wix5rNn-_P2Ry6-bFq6
"""

def mi_decorador(funcion):
    def wrapper():
        print("Algo sucede antes de la función.")
        funcion()
        print("Algo sucede después de la función.")
    return wrapper

@mi_decorador
def decir_hola():
    print("¡Hola!")

decir_hola()

def mi_decorador(funcion):
    def wrapper():
        print("Algo sucede antes de la función.")
        funcion()
        print("Algo sucede después de la función.")
    return wrapper

@mi_decorador
def decir_hola():
    print("¡Hola!")

# **CORRECCIÓN AQUÍ:** Se llama a la función sin pasar argumentos
decir_hola()
# La línea original era: decir_hola(holaaa)

def mi_decorador(funcion):
    def wrapper():
        print("vamos a sumar dos numeros.")
        funcion()
        print("se realizo la operacion")
    return wrapper
@mi_decorador
def sumar():
    print(11+3)
sumar()

def repetir(n):
    def decorador(func):
        def envoltura(*args, **kwargs):
            for _ in range(n):
                func(*args, **kwargs)
        return envoltura
    return decorador


@repetir(1)
def saludar(nombre):
    print(f"Hola, {nombre}!")


saludar("jonathan")

def repetir(n):
    def decorador(func):
        def envoltura(*args, **kwargs):
            for _ in range(n):
                func(*args, **kwargs)
        return envoltura
    return decorador

@repetir(5)
def saludar(nombre):
    print(f"buen dia, {nombre}!")

saludar("Leonel")

from functools import wraps

def mi_decorador(func):
    @wraps(func)
    def envoltura(*args, **kwargs):
        print("🔹 Antes de ejecutar la función")
        resultado = func(*args, **kwargs)
        print("🔹 Después de ejecutar la función")
        return resultado
    return envoltura


@mi_decorador
def saludar(nombre):
    print(f"Hola, {nombre}!")

saludar("Carlos")