# -*- coding: utf-8 -*-
"""U4 - Tema 2 .-  Generadores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epOgpNGBbSgy1-nCq8jahfgUAL0qV8h1
"""

def generador_pares(limite):
    num = 0
    while num < limite:
        yield num
        num += 3

for impar in generador_pares(20):
    print(impar)

def contar_hasta(n):
    for i in range(n):
        yield i

for numero in contar_hasta(5):
    print(numero)

gen = (x**2 for x in range(10))
print()

gen = (x**2 for x in range(10))

for valor in gen:
    print(valor)